services:
  - type: pgsql
    name: mothership-database
    region: oregon
    plan: starter
    databaseName: mothership
    databaseUser: mothership

  - type: job
    name: mothership-migrate
    env: node
    plan: starter
    region: oregon
    buildCommand: pnpm install --frozen-lockfile
    startCommand: pnpm migrate
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mothership-database
          property: connectionString
    
  - type: redis
    name: mothership-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: noeviction
    
  - type: web
    name: mothership-api
    env: node
    plan: starter
    region: oregon
    buildCommand: pnpm install --frozen-lockfile && pnpm -C packages/shared run build && pnpm -C packages/db run build && pnpm -C apps/api run build
    startCommand: node apps/api/dist/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mothership-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mothership-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
  - type: web
    name: mothership-frontend
    env: node
    plan: starter
    region: oregon
    buildCommand: pnpm install --frozen-lockfile && pnpm -C apps/frontend run build
    startCommand: pnpm -C apps/frontend start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://mothership-api.onrender.com
  - type: worker
    name: mothership-workers
    env: node
    plan: starter
    region: oregon
    buildCommand: pnpm install --frozen-lockfile && pnpm -C packages/shared run build && pnpm -C packages/db run build && pnpm -C apps/workers run build
    startCommand: node apps/workers/dist/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mothership-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mothership-redis
          property: connectionString
      - key: GOOGLE_MAPS_API_KEY
        sync: false

